### ISSUE TITLE
pLink issues in chapter04

### ISSUE THREAD

**Issue by timyerg** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#12]
Dear Tiago Antao!
First of all thank you for an excellent book. I read your topic on Qiime2 forum and bought your book a year ago but was busy and now I am following it chapter by chapter and running notebooks you provided.
In Chapter04 I encountered some problems with pLink.
I downloaded and processed necessary files, installed pLink v 2.3.1, imported os as it is indicated in notebook and tried to run the cell:
```
os.system('plink --recode --file hapmap3_r2_b36_fwd.consensus.qc.poly --noweb --out hapmap10 --thin 0.1 --geno 0.1')
os.system('plink --recode --file hapmap3_r2_b36_fwd.consensus.qc.poly --noweb --out hapmap1 --thin 0.01 --geno 0.1')
```
but no output files were produced (only got number 256 in notebbok output window).

Then I tried to run it directly:
```
!plink --recode --file hapmap3_r2_b36_fwd.consensus.qc.poly --noweb --out hapmap10 --thin 0.1 --geno 0.1
!plink --recode --file hapmap3_r2_b36_fwd.consensus.qc.poly --noweb --out hapmap1 --thin 0.01 --geno 0.1
```
This time, I got error:
`FileNotFoundError: [Errno 2] No such file or directory: '--recode'
`
I also tried to downgrade pLink to v1.9, but still it is not producing anything as output files with os.system and giving an error with running directly in notebook 

I am using Ubuntu 20.04, Jupyter lab, anaconda with Python 3.7

Thank you in advance

**Comment by tiagoantao** [comment]
This works OK with the plink version that I have here.
Given that there are several applications called plink, where did you download your plink code from?

**Comment by timyerg** [comment]
I used command:
`pip install plink`
to install plink on my machine.
I tried to install it via conda, but encountered some compatibility issues.
Can it be because I am using  Python 3.7?

**Comment by timyerg** [comment]
Update:
Created a new environment with python 3.6:
`conda create -n python-3_6 python=3.6
`
Installed  plink with conda within the new environment:
`conda install -c bioconda plink
`
Then installed  Biopython and Jupyter lab with conda.

Now everything is working, so I guess the problem was in combination of Python 3.7 and pip installation.
Thank you for your response.
