### ISSUE TITLE
Some of the download links using in Chapter03 returns 404 error

### ISSUE THREAD

**Issue by nkimoto** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#17]
First of all thank you for an excellent book. 
In Chapter03, it seems that some of the download links ([VectorBase](http://www.vectorbase.org)) are not exist yet.

For example, 
- Chapter03/Low_Quality.ipynb https://www.vectorbase.org/download/anopheles-atroparvus-ebroscaffoldsaatre1fagz
- Chapter03/Annotations.ipynb http://www.vectorbase.org/download/anopheles-gambiae-pestbasefeaturesagamp42gff3gz

Could you check the notebook?
Thank you in advance.

**Comment by tiagoantao** [comment]
Sincere apologies for the delay.
This should now be sorted.
Tell me if you still have problems
