### ISSUE TITLE
Bio.Alphabet not available any more

### ISSUE THREAD

**Issue by RAnytime** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#20]
Dear all, as Bio.Alphabet has been removed, some parts of "Chapter02/Basic_Sequence_Processing.ipynb" can't work properly. What has to be changed in the code? It would be a nice exercise. But I didn't solve it except deleting the lines causing errors. Perhaps there is a better way?
Best
Ulrich

**Comment by tiagoantao** [comment]
The book was written in 2018, so it mostly tracks the state of libraries at that time. This is not a repository that will be maintained ad infinitum, but related to the book at the point it was written.

That being said, If someone submits PRs for newer versions of libraries I will merge them.
