### ISSUE TITLE
InvalidVersionSpecError: Invalid version spec: =2.7

### ISSUE THREAD

**Issue by rajeshgadepalli** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#21]
Getting error, when running the below command

docker build -t bio https://raw.githubusercontent.com/PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition/master/docker/Dockerfile

> [ 8/17] RUN conda install -y -c conda-forge statsmodels:
#10 0.734 Solving environment: ...working... failed
#10 96.24
#10 96.24 InvalidVersionSpecError: Invalid version spec: =2.7
#10 96.24
------
executor failed running [/bin/sh -c conda install -y -c conda-forge statsmodels]: exit code: 1

**Comment by ggmariaelena** [comment]
I have the same issue.

**Comment by tiagoantao** [comment]
I was on vacation, so I took some time to address this, sorry.

This should not be sorted. Feel free to open a new ticket if not
