### ISSUE TITLE
rpy2 incompatible with new Python

### ISSUE THREAD

**Issue by wendyol** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#23]
I was able to add all of the needed software using Anaconda, however, when I tried Ch1 through Jupyter Notebook, I kept getting an error that the Python used by Anaconda is no longer compatible with rpy2. Is there some way to fix this? 

Thanks,

Wendy

**Comment by tiagoantao** [comment]
You can try using the docker image provided.
This works with the versions of the software at the time of the book release, but as time goes by there might be some incompatibilities emerging.
