### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by 0x29aw** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#24]
Hi, today when I try to build docker image, it fails. Probably problem is with undefined versions of downloaded libraries, and after time those libraries (their newest versions) is incompatible with environment(?).
Or do you can upload builded image somewhere?

**Comment by tiagoantao** [comment]
The third edition of the book will be out soon, that is the currently maintained repository. You can access that repository for free

**Comment by 0x29aw** [comment]
> 

Thanks for reply. Repo for Third edition will be work correctly with 2nd edition book?

**Comment by tiagoantao** [comment]
A part of the code is similar, indeed.
