### ISSUE TITLE
VCF_files_protocol_not_supported

### ISSUE THREAD

**Issue by zjq101** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#25]
Hello.
When I tried to install the VCF file in chapter2,
I got the following error:
```
[E::hts_open_format] Failed to open file "ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/supporting/vcf_with_sample_level_annotation/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5_extra_anno.20130502.genotypes.vcf.gz" : Protocol not supported  

Could not open "ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/supporting/vcf_with_sample_level_annotation/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5_extra_anno.20130502.genotypes.vcf.gz": Protocol not supported
```
I have installed tabix and bgzip.

Failed in both command line and is vscode
Are are any possible reasons and solutions?
Thanks in advance.

**Comment by tiagoantao** [comment]
The second edition of the book is not maintained anymore. You can find new URLs on the 3rd edition of the book (Chapter 3 is the equivalent). You don't need to get the new edition of the book, just download the free repository.

See here: https://github.com/PacktPublishing/Bioinformatics-with-Python-Cookbook-third-edition
