### ISSUE TITLE
downloading link for data provided in each chapter

### ISSUE THREAD

**Issue by shaghayeghsoudi** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#26]
Hello,
I just recently purchased the third edition of Bioinformatics with python cookbook and I want to practice examples codes with the data in each chapeter. I could not download the datasets you have used in the chapters in the book. Is there any other link to download the dataset?
It seems the ftp links are not working anymore!
This link has all of the data sets in each chapter but I cannot get it 
https://github.com/PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition/blob/master/Datasets.ipynb

Can you please provide a link that I could download data for each chapter?
Thank you

**Comment by tiagoantao** [comment]
The second edition of the book is not supported anymore. Please check the repo of the third edition
