### ISSUE TITLE
Purpose of chrom_seq in-parameter in get_sequence function in Chapter03/Getting_Gene.ipynb?

### ISSUE THREAD

**Issue by ljmesi** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#3]
`chrom_seq` in-parameter is never used in `get_sequence`-function in `Chapter03/Getting_Gene.ipynb`. 
Should `my_seq` be switched to `chrom_seq` in:
```
my_cds = Seq.Seq(str(my_seq[CDS.start - 1: CDS.end]), alphabet=Alphabet.IUPAC.unambiguous_dna)
```
?

**Comment by tiagoantao** [comment]
My sincere apologies for the extreme delay in answering.
Actually the function should never use a global variable, so I changed the implementation to refer `chrom_seq`

**Comment by tiagoantao** [comment]
My sincere apologies for the extreme delay in answering.
Actually the function should never use a global variable, so I changed the implementation to refer `chrom_seq`
