### ISSUE TITLE
Accessing_Databases.ipynb

### ISSUE THREAD

**Issue by alp78** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#4]
In [5]:
id_list = rec_list['IdList']
hdl = Entrez.efetch(db='nucleotide', id=id_list, rettype='gb')

- this will make the next statement fail, should pass retmax argument:

In [5]:
id_list = rec_list['IdList']
hdl = Entrez.efetch(db='nucleotide', id=id_list, rettype='gb', retmax=rec_list['Count'])

**Comment by tiagoantao** [comment]
Thanks, I made this change!
