### ISSUE TITLE
biobase / ggplot2

### ISSUE THREAD

**Issue by alp78** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#6]
- this command won't work in Debian/Ubuntu:

apt-get r-bioc-biobase r-cran-ggplot2

- only way i could install these two libraries is from R prompt:
 
source("http://bioconductor.org/biocLite.R")
biocLite()
install.packages('ggplot2')

**Comment by tiagoantao** [comment]
What version of ubuntu do you have?

**Comment by alp78** [comment]
18.04.3
