### ISSUE TITLE
Working_with_FASTQ / gzip

### ISSUE THREAD

**Issue by alp78** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#7]
**recs = SeqIO.parse(gzip.open('SRR003265.filt.fastq.gz'), 'fastq')**
- this won't work as gzip will try to open the file by default in binary mode, the text mode needs to be specified: 

**recs = SeqIO.parse(gzip.open('SRR003265.filt.fastq.gz', 'rt'), 'fastq')**

**Comment by tiagoantao** [comment]
Exactly which cell has this, as far as I can see, all have `rt`?

**Comment by alp78** [comment]
book :)
