### ISSUE TITLE
Working_with_FASTQ / seaborn

### ISSUE THREAD

**Issue by alp78** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#8]
1) boxplot
**sns.boxplot(vps, ax=ax)**
- since i don't know when the format of passing data to boxplot requires the keyword 'data':

**sns.boxplot(data=vps, ax=ax)**

2) subplot
alway nice to provide a good format for the plot, default is too small, e.g.:
**fig, ax = plt.subplots(figsize=(14,8))**

3) set_xticklabels
**ax.set_xticklabels([str(x) for x in range(26, max(qual_pos.keys()) + 1)])**
- this will print the list of labels before the plot, better assign it to a dummy variable, so only graph with labels shows up:
**d = ax.set_xticklabels([str(x) for x in range(26, max(qual_pos.keys()) + 1)])**

**Comment by tiagoantao** [comment]
Confused here also: the `data` is there, also for a `figsize` and `subplots`

**Comment by alp78** [comment]
same, probably book ref
