### ISSUE TITLE
Working_with_FASTQ / sort dictionary

### ISSUE THREAD

**Issue by alp78** [PacktPublishing/Bioinformatics-with-Python-Cookbook-Second-Edition#9]
poses = qual_pos.keys()
**poses.sort()**
- will only work in Python 2.5
- in Python 3:

**poses = sorted(qual_pos.keys())**

**Comment by tiagoantao** [comment]
That is why the code is slightly different than that: 
`poses = list(qual_pos.keys())`
The list makes `sort` work.

Question: I suppose you are following the book and not the notebooks? Because these errors might be in the book (I do not have the book here to check)

**Comment by alp78** [comment]
i'm not sure the source now, but probably the book yes, can be closed then
